### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by syepes** [markchadwick/graphite-relay#2]
Hello,

I would like to use this graphite-relay app with one of my projects, but the issue is that I have not been able to lunch the relay server (graphite-relay-0.2.7.jar).

Is it necessary to have any additional jar in the classpath?
# java -version

java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b20)
Java HotSpot(TM) 64-Bit Server VM (build 23.0-b21, mixed mode)
# java -jar graphite-relay-0.2.7.jar -c graphite-relay.properties

Loading graphite-relay.properties
2012-06-05 13:00:22,741 [main           ] INFO  Main                           - Backend Strategy: class graphite.relay.backend.strategy.ConsistentHash
2012-06-05 13:00:22,742 [main           ] INFO  Main                           - Overflow Handler: class graphite.relay.overflow.BitchingOverflowHandler
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=aggregation.config) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=aggregation.config)
    for parameter 2 at graphite.relay.aggregation.Aggregator.<init>(Aggregator.scala:19)
  while locating graphite.relay.aggregation.Aggregator

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
        at graphite.relay.Main$.main(Main.scala:43)
        at graphite.relay.Main.main(Main.scala)

Thanks in advance for any help.

**Comment by markchadwick** [comment]
It's expecting aggregation.config to be in the settings file -- its value should be the path to a Graphite-style aggregation config file. See here: https://github.com/markchadwick/graphite-relay/tree/feature/aggregation2/util

However, it likely shouldn't do that by default, and there are no docs, so I'll leave this open.

**Comment by syepes** [comment]
Thanks for the rapid response, that was the missing piece ;-) Now it starts perfectly.
